#---
#### vars folder
#apt_cache_valid_time: 86400
#
php_fpm_pools:
 - name: www
   user: www-data
   group: www-data
   listen: /var/run/php5-fpm.sock
   chdir: /
#
#php_fpm_pool_defaults:
#  pm: dynamic
#  pm.max_children: 5
#  pm.start_servers: 2
#  pm.min_spare_servers: 1
#  pm.max_spare_servers: 3

#php_fpm_apt_packages:
#  - php5-fpm

#php_fpm_yum_packages:
#  - php-fpm

#php_fpm_default_pool:
#  delete: no
#  name: www.conf

php_fpm_default_pool:
  delete: yes
  name: www3

#php_fpm_ini:
# - option: "engine"
#   section: "PHP"
#   value: "1"
# - option: "error_reporting"
#   section: "PHP"
#   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
# - option: "ldap.max_links"
#   section: "ldap"
#   value: "1"

#php_fpm_config:
# - option: "error_log"
#   section: "global"
#   value: "/var/log/php5-fpm.log"

#### defaults folder
#env:
# RUNLEVEL: 1
#---
#php_fpm_ini_path: /etc/php5/fpm/php.ini
#php_fpm_config_path: /etc/php5/fpm/php-fpm.conf
#php_fpm_pool_d: /etc/php5/fpm/pool.d

php_fpm_binary_name: php5-fpm
#php_fpm_service_name: php5-fpm
#
#php_fpm_pid_file: /var/run/php5-fpm.pid
