- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Updating apt-get cache, then upgrading with apt-get
  apt: update_cache=yes
  apt: upgrade="{{ upgrade['type'] }}"

