- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Updating apt-get cache
  apt: update_cache=yes
- name: Upgrading with apt-get
  apt: upgrade="{{ upgrade['type'] }}"

