nginx_sites:
  default:
     - listen 80 default_server
     - server_name _
     - root "/usr/share/nginx/html"
     - index index.html
     - location ~ \.(php)$ {
         try_files $uri =404;
         fastcgi_pass unix:/var/run/php5-fpm/sock;
         fastcgi_index index.php;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         include fastcgi_params;
       }
