supervisord_programs:
  - name: datadumper
    directory: "/home/ubuntu/frc/frc-scraper-cli/bin"
    command: "mono frc-scraper-cli.exe -dump"
    autostart: "true"
    autorestart: "true"
    user: root
    stdout_logfile: "/var/log/supervisor/frc-datadumper.stdout.log"
    stderr_logfile: "/var/log/supervisor/frc-datadumper.stderr.log"
#  - name: rabbitmq
#    command: "/usr/sbin/rabbitmq-server"
#    autostart: "true"
#    autorestart: "true"
##    user: root
#    stdout_logfile: "/var/log/supervisor/rabbitmq.stdout.log"
#    stderr_logfile: "/var/log/supervisor/rabbitmq.stderr.log"
  - name: redis
    command: "/opt/redis/bin/redis-server /etc/redis/6379.conf"
    autostart: "true"
    autorestart: "true"
    user: root
    stdout_logfile: "/var/log/supervisor/redis.stdout.log"
    stderr_logfile: "/var/log/supervisor/redis.stderr.log"
#  - name: redis_sentinel
#    command: "/opt/redis/bin/redis-server /etc/redis/sentinel_26379.conf"
#    autostart: "true"
#    autorestart: "true"
#    user: root
#    stdout_logfile: "/var/log/supervisor/redis_sentinel.stdout.log"
#    stderr_logfile: "/var/log/supervisor/redis_sentinel.stderr.log"

supervisord_groups:
  - name: g_datadumper
    programs: "datadumper"
  - name: g_rabbitmq
    programs: "rabbitmq"
  - name: g_redis
    programs: "redis"
