---
- name: Creates directory for supervisor log
  file: path=/var/log/frc state=directory owner=root group=root mode=0775

- name: Creates directory for supervisor log
  file: path=/var/log/frc/datadumper state=directory owner=root group=root mode=0775

- name: Create shortcuts for supervisor
  file: src=/var/log/supervisor/frc-datadumper.stdout.log dest=/var/log/frc/datadumper/stdout.log owner=root group=root mode=0644 state=link force=yes

- name: Create shortcuts for supervisor
  file: src=/var/log/supervisor/frc-datadumper.stderr.log dest=/var/log/frc/datadumper/stderr.log owner=root group=root mode=0644 state=link force=yes

- name: Creates directory for redis log
  file: path=/var/log/redis state=directory owner=root group=root mode=0775
- name: Create shortcuts for redis
  file: src=/var/log/supervisor/redis.stderr.log dest=/var/log/redis/stderr.log owner=root group=root mode=0644 state=link force=yes
  file: src=/var/log/supervisor/redis.stderr.log dest=/var/log/redis/error.log owner=root group=root mode=0644 state=link force=yes
  file: src=/var/log/supervisor/redis.stdout.log dest=/var/log/redis/stdout.log owner=root group=root mode=0644 state=link force=yes
  file: src=/var/log/supervisor/redis.stdout.log dest=/var/log/redis/supervisor_redis.log owner=root group=root mode=0644 state=link force=yes
