---
- hosts: test
  sudo: true
  pre_tasks:
#    - name: Include variables for galaxy mivok0/users
#      include_vars: ./galaxy/roles/mivok0.users/vars/main.yml
#    - name: Include variables for galaxy stouts/rabbitmq
#      include_vars: ./galaxy/roles/Stouts.rabbitmq/vars/main.yml
#    - name: Include variables for galaxy stouts/redis
#      include_vars: ./galaxy/roles/Stouts.redis/vars/main.yml
#    - name: Include variables for galaxy jdauphant/nginx
#      include_vars: ./galaxy/roles/jdauphant.nginx/vars/main.yml
#    - name: Include variables for galaxy nbz4live/phpfpm
#      include_vars: ./galaxy/roles/nbz4live.php-fpm/vars/main.yml
#    - name: Include variables for galaxy f500/dumpall
#      include_vars: ./galaxy/roles/f500.dumpall/vars/main.yml
#    - name: Include variables for galaxy Stouts/elasticsearch
#      include_vars: ./galaxy/roles/Stouts.elasticsearch/vars/main.yml
#    - name: Include variables for galaxy avanov/supervisord
#      include_vars: ./galaxy/roles/avanov.supervisord/vars/main.yml
#    - name: Include variables for galaxy DavidWittman/redis
#      include_vars: ./galaxy/roles/DavidWittman.redis/vars/main.yml
  roles:
    - hostname
    - upgrade
    - mivok0.users
    - packages
    - Stouts.timezone
#    - Stouts.rabbitmq
#    - DavidWittman.redis
#    - Stouts.elasticsearch
#    - jdauphant.nginx
#    - nbz4live.php-fpm
#    - avanov.supervisord
    - f500.dumpall
  tasks:
#    - include: ./galaxy/roles/avanov.supervisord/tasks/main.yml
    - name: create fake 'nologin' shell
      file: path=/home/vagrant/{{ sites["freckles.io"]["name"] }} state=touch owner=root group=sys mode=0555
  vars:
  post_tasks:

