---
redis_version: stable
redis_maxmemory: 1gb
redis_maxmemory_policy: noeviction
redis_bind: 127.0.0.1
redis_port: 6379
redis_logfile: /var/log/redis/redis-server.log
redis_as_service: yes
redis_daemonize: "yes"

redis_sentinel: false
redis_sentinel_bind: 127.0.0.1
redis_sentinel_port: 26379
redis_sentinel_logfile: /var/log/redis/redis-sentinel.log
redis_sentinel_monitors:
  - name: master01
    host: 127.0.0.1
    port: 26379
    quorum: 2
    auth_pass: ant1r3z
    down_after_milliseconds: 30000
    parallel_syncs: 1
    failover_timeout: 180000
    notification_script: false
    client_reconfig_script: false
